# ## Appearance

# - Use true color
set-option -ga terminal-overrides ",xterm-256color:Tc"

# - Enable pointer support for switching panes and windows.
setw -g mouse on
set-option -g -q mouse on


# ## Copy Mode

# - Use 'vi' bindings rather than 'emacs'.
setw -g mode-keys vi

# - More settings to make copy-mode more vim-like.
unbind [
bind Escape copy-mode


# ## Other settings

# - Remove delay on hitting escape
set -sg escape-time 10


# ## Plugins

# - Installs and loads TMUX plugins.
set -g @plugin 'tmux-plugins/tpm'
# - A set of tmux options that should be acceptable to everyone.
set -g @plugin 'tmux-plugins/tmux-sensible'
# - Tmux plugin for controlling panes. Adds standard pane navigation bindings.
set -g @plugin 'tmux-plugins/tmux-pain-control'
# - Tmux plugin for copying to system clipboard.
set -g @plugin 'tmux-plugins/tmux-yank'
# - Plugin that highlights when you press tmux prefix key.
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
# - Auto-tiling layout
set -g @plugin 'saysjonathan/dwm.tmux'


# - Initialize TMUX plugin manager. Plugins are loaded here, so anything that
#   overrides plugin settings must come after this line.
run '~/.tmux/plugins/tpm/tpm'


# ## Plugin overrides

# - dwm.tmux settings
# Set the size of the main pane with dwm.tmux
set-option -wg @mfact 67
# Leave M-J/M-K for apps, e.g. Magit+Evil rebase mode via Emacs'
# shift-translation in
# https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Sequence-Input.html
unbind -n M-J
unbind -n M-K
# Leave M-b for backward-word in readline
unbind -n M-b
